service: my-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: src/handler.handler
    events:
        - httpApi:
            path: /
            method: get